### ISSUE TITLE
dejar a pepita en paz y cambiarle los sprites al personaje

### ISSUE THREAD

**Issue by franngo** [obj1unq/2024s2-tp-grupal-juego-grupo-2-2#18]
Pepita ya esta harta!
Hay que buscar sprites para el pj sin arma, y, después, editar ese sprite para agregarle encima los 3 tipos de arma como hicimos con pepita (o encontrar en internet un mismo sprite que esté en una versión sin arma, con espada, con arco y flecha, y con martillo de guerra, lo cual no creo que exista)
También podríamos considerar sprites yendo hacia arriba, abajo, izquierda y derecha (al menos para el pj).

**Comment by Artifrex** [comment]
jamas! el jefe final es pepita (?
